### ISSUE TITLE
Memory Leak in Latest React Native

### ISSUE THREAD

**Issue by satheshrgs-rksv** [callstack/react-native-brownfield#80]
## Environment

Hi
With the latest react native brownfield, I'm facing memory leak. Attaching the screenshot for reference. Can be repro'ed using the master code

![Screenshot 2024-06-27 at 20 41 04](https://github.com/callstack/react-native-brownfield/assets/171787196/b55243fc-52ba-49e0-a1a9-86df3470013a)

**Comment by okwasniewski** [comment]
Hey, thanks for opening the issue. I will take a look at this 👍🏻

**Comment by harsh-rksv** [comment]
To add more context our on issue faced:
To support Android 14, we had to upgrade React to a version above 0.73. We were using the Brownfield project as a reference for our integration (thanks for this excellent brownfield repo 🤝 ). However, after the upgrade, our automation has detected memory leaks throughout our application.

Could you please provide a fix for this issue at the earliest? The Android 14 deadline is approaching quickly, and a prompt resolution would be greatly appreciated.

**Comment by satheshrgs-rksv** [comment]
@okwasniewski https://github.com/facebook/react-native/issues/45217#issuecomment-2208877868

**Comment by okwasniewski** [comment]
This issue is a regression in the core with some PR coming up to fix it. I'm going to close this issue as this needs to be fixed in core.

**Comment by yzhe554** [comment]
> This issue is a regression in the core with some PR coming up to fix it. I'm going to close this issue as this needs to be fixed in core.

@okwasniewski are there links for the coming PRs/tickets? I'd like to follow this up.
